[ 57%] Building CXX object CMakeFiles/pycalonder.dir/src/py.cpp.o
In file included from
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:18:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:4:
error: \u2018SparseSignature\u2019 was not declared in this scope
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:4:
error: wrong number of template arguments (2, should be 1)
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/include/calonder_descriptor/matcher.h:14:
error: provided for \u2018template<class Data> class
features::BruteForceMatcher\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:
In function \u2018PyObject* make_wrapped_BruteForceMatcher(PyObject*,
PyObject*)\u2019:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:77:
error: \u2018SparseSignature\u2019 was not declared in this scope
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:77:
error: wrong number of template arguments (2, should be 1)
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/include/calonder_descriptor/matcher.h:14:
error: provided for \u2018template<class Data> class
features::BruteForceMatcher\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:
At global scope:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:85:
error: \u2018SparseSignature\u2019 does not name a type
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:
In function \u2018void wrapped_SparseSignature_dealloc(PyObject*)\u2019:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:99:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/generated.i:99:
error: expected class-name before \u2018(\u2019 token
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:
In function \u2018PyObject* getSparseSignature(PyObject*, PyObject*)\u2019:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:103:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:103:
error: expected type-specifier before \u2018SparseSignature\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:103:
error: expected `;' before \u2018SparseSignature\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:100:
warning: unused variable \u2018pc\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:
In function \u2018PyObject*
wrapped_BruteForceMatcher_addSignature(PyObject*, PyObject*)\u2019:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:137:
error: request for member \u2018addSignature\u2019 in \u2018*
pm->wrapped_BruteForceMatcher_t::c\u2019, which is of non-class type
\u2018int\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:137:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:
In function \u2018PyObject* wrapped_BruteForceMatcher_findMatch(PyObject*,
PyObject*)\u2019:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:156:
error: request for member \u2018findMatch\u2019 in \u2018*
pm->wrapped_BruteForceMatcher_t::c\u2019, which is of non-class type
\u2018int\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:156:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:158:
error: request for member \u2018findMatchPredicated\u2019 in \u2018*
pm->wrapped_BruteForceMatcher_t::c\u2019, which is of non-class type
\u2018int\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:158:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:
In function \u2018PyObject* wrapped_SparseSignature_dump(PyObject*,
PyObject*)\u2019:
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:170:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:171:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/src/py.cpp:172:
error: \u2018struct wrapped_SparseSignature_t\u2019 has no member named
\u2018c\u2019
make[3]: *** [CMakeFiles/pycalonder.dir/src/py.cpp.o] Error 1
make[3]: Leaving directory
`/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/build'
make[2]: Leaving directory
`/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/build'
make[1]: Leaving directory
`/home/rosbuild/.hudson/jobs/personalrobots-update/workspace/personalrobots/vision/calonder_descriptor/build'
make[2]: *** [CMakeFiles/pycalonder.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
[rosmakeall-buildfail] Build of calonder_descriptor failed
